server:
  port: 8084

spring:
  application:
    name: FinanceMgmtGrant
  datasource:
    url: jdbc:postgresql://${DB_HOST:54.234.94.158}:5432/finmgt
    username: forest
    password: ENC(FD/vdt4Os8rQ2smS+aShXJEdv+gH0DEWjA2fjDBs4HQ3r+/4M3M4b0hdjayL/eW6)
    driver-class-name: org.postgresql.Driver
    test-while-idle: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 60000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: fin_mgmt
---
spring:
  config:
    activate:
      on-profile: jenkins-docker

testing:
  sonar:
    url: "host.docker.internal"

---
spring:
  profiles:
    active: jenkins-docker